version: "3.3"

services:
  # api:
    # build: ./app
    # container_name: api_c
    # ports:
    #   - '4000:4000'
    # volumes:
    #   - ./api:/app
    #   - ./app/node_modules

  react-docker:
    build: ./react-docker
    container_name: reactdocker
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true 