version: "3.3"

services:
  frontend:
    build: ./react-docker
    image: simple-react-app:latest
    container_name: rect-app1
    stdin_open: true
    volumes:
      - ./react-docker:/usr/src/app
      - /usr/src/app/react-docker/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    restart: unless-stopped
    command: npm start